# refer to http://www.yaml.org/spec/1.1/ for clarification on YAML collections
openpinnedtab:
  path: openpinnedtab
  custom_layout:
    column_count: 24
    column_width: 12
    gutter_width: 10
  plugins:
    - fancy-type
